name: Trigger auto deployment for grocerys-front

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ buho_01102023 ]
    paths:
    - '**'
    - '.github/workflows/grocerys-front-AutoDeployTrigger-7cb79d9c-202d-4018-a510-18973ce5a6f0.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GROCERYSFRONT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: groceryscentrocambiario.azurecr.io
          registryUsername: ${{ secrets.GROCERYSFRONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GROCERYSFRONT_REGISTRY_PASSWORD }}
          containerAppName: grocerys-front
          resourceGroup: SistemaDIV
          imageToBuild: groceryscentrocambiario.azurecr.io/grocerys-front:${{ github.sha }}
          

     

